logs\*.log

start /low /min /wait PLUS80W username/password@beta8.world @ds-o.sql
start /low /min /wait PLUS80W username/password@beta8.world @dp-0.sql
start /low /min /wait PLUS80W username/password@beta8.world @dp-1.sql
start /low /min /wait PLUS80W username/password@beta8.world @dp-1_2.sql
start /low /min /wait PLUS80W username/password@beta8.world @dp-2.sql

start /low /min /wait PLUS80W username/password@beta8.world @lr-0.sql
start /low /min /wait PLUS80W username/password@beta8.world @lr-1.sql
start /low /min /wait PLUS80W username/password@beta8.world @lr-2.sql

start /low /min /wait PLUS80W username/password@beta8.world @jr-0.sql
start /low /min /wait PLUS80W username/password@beta8.world @jr-1.sql
start /low /min /wait PLUS80W username/password@beta8.world @jr-2.sql
start /low /min /wait PLUS80W username/password@beta8.world @jr-3.sql
start /low /min /wait PLUS80W username/password@beta8.world @jr-4.sql

start /low /min /wait PLUS80W username/password@beta8.world @int-0.sql
